# Generated by Django 5.2.9 on 2026-01-23 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0007_ventagarage_documento_interes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursosrealizados',
            options={'ordering': ['-fechainicio']},
        ),
        migrations.AlterModelOptions(
            name='reconocimientos',
            options={'ordering': ['-fechareconocimiento']},
        ),
        migrations.AlterModelOptions(
            name='ventagarage',
            options={'ordering': ['-fecha_publicacion']},
        ),
        migrations.AddField(
            model_name='ventagarage',
            name='fecha_publicacion',
            field=models.DateField(auto_now_add=True, default='2025-01-01', verbose_name='Fecha de publicación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cursosrealizados',
            name='totalhoras',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='datospersonales',
            name='numerocedula',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_cedula', message='La cédula debe tener 10 dígitos numéricos.', regex='^\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='ventagarage',
            name='valordelbien',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
